### ISSUE TITLE
intl_translation >=0.17.7 depends on old version of package intl 

### ISSUE THREAD

**Issue by shic** [dart-lang/intl_translation#136]
These are the packages that  we are using.

```
dependencies:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^4.0.2
  intl_translation: ^0.17.10+1

```

Got error

```
Running "flutter pub get" in leopard...                         

Because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0 and leopard depends on intl ^0.17.0, intl_translation >=0.17.7 is forbidden.
So, because leopard depends on intl_translation ^0.17.10+1, version solving failed.
pub get failed (1; So, because leopard depends on intl_translation ^0.17.10+1, version solving failed.)
Process finished with exit code 1
```
