### ISSUE TITLE
not working with angular dart 5

### ISSUE THREAD

**Issue by zreptil** [dart-lang/intl_translation#45]
At my current project the @i18n-annotations in the template-files are not extracted when building the app and so no string of the files shows up in the arb-file. The project uses the following pubspec.yaml:

```
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.1
  intl: ^0.15.7
  crypto: ^2.0.6

dev_dependencies:
  build_runner: ^0.10.3
  build_web_compilers: ^0.4.0+4
  sass_builder: ^2.0.1
  intl_translation: ^0.17.0
```

Are there any known issues with versions of any of the dependencies? I also tried build_runner 1.0.0, but the rest of my project is not happy with this, so i need to stay at 0.10.3.

**Comment by alan-knight** [comment]
Leon, do you know anything about this?

**Comment by leonsenft** [comment]
@zreptil Did you follow the steps in https://github.com/dart-lang/angular/blob/master/examples/i18n/README.md?

When running [extract_to_arb](https://github.com/dart-lang/angular/blob/master/examples/i18n/README.md#extract-messages) make sure to include the generated `.template.dart` files.

**Comment by leonsenft** [comment]
Sorry I didn't notice you were on angular v5.0.0.

Internationalization in templates (support for the `@i18n` annotations) was released in [v5.1.0](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#new-features). That said, we developed the feature throughout v5.0.0-alpha+ behind a flag, so it's technically possible to enable without upgrading to v5.1.0, but depending on which version of 5.0.* you have, you may get different/incomplete behavior.

**Option 1**
Upgrade your dependency on `angular` to v5.1.0.

**Option 2**
Keep your dependency on `angular` at v5.0.0, and enable internationalization via the flag.

```yaml
# build.yaml
targets:
  $default:
    builders:
      angular:
        options:
          i18n: True
```
