### ISSUE TITLE
Using flutter_test 0.9.4 in combination with intl_translation 0.17.2 fails to resolve

### ISSUE THREAD

**Issue by haarts** [dart-lang/intl_translation#46]
I've got a version conflict between `flutter_test` and `intl_translation`. 

pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  intl_translation: 0.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
```

Running `flutter packages get`:

```
Because every version of flutter_test from sdk depends on analyzer 0.32.4 and intl_translation >=0.17.2 depends on analyzer ^0.33.0-alpha.0, flutter_test from sdk is incompatible with intl_translation >=0.17.2.
So, because kolibri depends on both intl_translation ^0.17.2 and flutter_test any from sdk, version solving failed.
```

Doctor:
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.9.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
```

Dart version `2.1.0-dev.5.0.flutter-a2eb050044`.
